// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7iYIS_D3MltbOyUvjPTObGAuFQf-Cg3Y',
    appId: '1:518426399994:web:f8a34a4aef1b962471a543',
    messagingSenderId: '518426399994',
    projectId: 'rmp-app-2-08-2023',
    authDomain: 'rmp-app-2-08-2023.firebaseapp.com',
    storageBucket: 'rmp-app-2-08-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2lOCE9DtKumVDnA08bNLNVzMMou0yG8I',
    appId: '1:518426399994:android:f93013959ec31f3a71a543',
    messagingSenderId: '518426399994',
    projectId: 'rmp-app-2-08-2023',
    storageBucket: 'rmp-app-2-08-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAfYxW9bHnX2JYlwgjTh08HA1vvnRXHg',
    appId: '1:518426399994:ios:b0a778cbb3e5049f71a543',
    messagingSenderId: '518426399994',
    projectId: 'rmp-app-2-08-2023',
    storageBucket: 'rmp-app-2-08-2023.appspot.com',
    iosClientId: '518426399994-r7ou91rotff6j2m84kpkka4enn4tqn5p.apps.googleusercontent.com',
    iosBundleId: 'com.restraurantmp.rmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPAfYxW9bHnX2JYlwgjTh08HA1vvnRXHg',
    appId: '1:518426399994:ios:b0a778cbb3e5049f71a543',
    messagingSenderId: '518426399994',
    projectId: 'rmp-app-2-08-2023',
    storageBucket: 'rmp-app-2-08-2023.appspot.com',
    iosClientId: '518426399994-r7ou91rotff6j2m84kpkka4enn4tqn5p.apps.googleusercontent.com',
    iosBundleId: 'com.restraurantmp.rmp',
  );
}
